import Head from 'next/head'
import Image from 'next/image'
import { Plus_Jakarta_Sans } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { HStack, VStack, Text, Center, Spacer, Box } from '@chakra-ui/react'
import Notif from '@/ui/Notif'

const jakartaSans = Plus_Jakarta_Sans({weight:['500','700'], subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Notifications Page</title>
        <meta name="description" content="Generated by ida Nido" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <main className={jakartaSans.className}>
        <Box w='100vw' h='100vh' bg="brand.paleGreyBlue" pt='100px'>
          <VStack w='50%'  p="15px" mx="auto" bg="white" borderRadius="15px" >
            <HStack w='100%'>
              <Text fontSize="20px" color="brand.darkBlue">Notifications</Text>
              <Center boxSize='25px' bg="blue.700" color='white' borderRadius="5px">
                <Box as='span' fontWeight='bold' fontSize='lg'>
                  3
                </Box>
              </Center>
              <Spacer />
              <Text>Mark all as read</Text>
            </HStack>
            <Notif  name="Mark Webber"
                    isRead={false}
                    srcImg="/images/avatar-mark-webber.webp"
                    alt="mark-webber"
                    content="reacted to your recent post 
                    "
                    post="My first tournament today!"
                    time="1m ago" />
            
          </VStack>
        </Box>
        
      </main>
    </>
  )
}
